Upgrade to 0.19
BrianHicks/elm-trend pull request #1
Opened 2018-08-29 16:51 UTC by w0rm

2018-08-29 16:58 UTC, w0rm commented
Tests definitely passed locally :(

2018-08-29 17:14 UTC, BrianHicks requested changes
this is looking great, thank you for taking the time to upgrade it! Just a couple comments about meta-stuff. 😄

2018-08-29 17:14 UTC, BrianHicks commented on .gitignore
> +.DS_Store
platform-specific ignores belong in a global config, I'd rather keep them out of this repo. :)

2018-08-29 17:14 UTC, BrianHicks commented on .gitignore
> +package-lock.json
shouldn't we check in package-lock.json?

2018-08-29 17:14 UTC, BrianHicks commented on .travis.yml
> +script: make
do you not have to build documentation.json separately in 0.19? I'd like that to stay in CI if possible.

Also, AFAICT the sysconfcpus bug is not fixed in 0.19. Did you find differently?

2018-08-29 17:14 UTC, BrianHicks commented on src/Trend/Math.elm
> +    stddev [ 1, 2, 3, 4, 5 ]
thanks for the catch here!

2018-08-29 17:19 UTC, w0rm commented on .gitignore
> +package-lock.json
It's a huge file to publish, but I can check it in if you want!

2018-08-29 17:22 UTC, w0rm commented on .travis.yml
> +script: make
1) `make` runs `make all` that includes `documentation.json test`.
2) I removed sysconfcpus from my game and it compiled within a minute. It took a bit more than a minute for https://travis-ci.org/BrianHicks/elm-trend/builds/422174067 to complete, so I don't find this necessary, but I can restore it if you want.

2018-08-29 17:22 UTC, w0rm commented on .gitignore
> +.DS_Store
Removed!

2018-08-29 17:23 UTC, BrianHicks commented on .travis.yml
> +script: make
as long as it's under 5 I think we're good. Thanks 😄

2018-08-29 17:24 UTC, BrianHicks commented on .gitignore
> +package-lock.json
I dunno! Is it the right thing to do in this case? I'm less familiar with how node works—I'm only using it as a delivery mechanism for Elm binaries in this project :joy:

2018-08-29 18:03 UTC, w0rm commented
@BrianHicks I believe I addressed all your comments!

2018-08-29 18:06 UTC, BrianHicks commented
yeah, I think you did! Do you think it'd be fine to just publish the new version on 0.19 since there are no substantial changes? I'm not sure how it will need to be tagged. Since you've done a couple of them, and guidance?

2018-08-29 18:06 UTC, BrianHicks commented
(I'll merge when we have a solid plan there.)

2018-08-29 18:06 UTC, BrianHicks approved these changes

2018-08-29 18:44 UTC, w0rm commented
Just merge, run `elm bump`, commit the change, then tag on github the same way as before, and publish with `elm publish`.

2018-08-30 13:13 UTC, BrianHicks commented
Great, thank you! I'll merge and do that soon :)

> On Aug 29, 2018, at 1:44 PM, Andrey Kuzmin <notifications@github.com> wrote:
> 
> Just merge, run elm bump, commit the change, then tag on github the same way as before, and publish with elm publish.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/BrianHicks/elm-trend/pull/1#issuecomment-417062434>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAVsSQ6rwBOrfjrGK_uSLr63TN6PR0Jbks5uVuEOgaJpZM4WR8VY>.
>

2018-08-31 18:07 UTC, merged